language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
deploy:
  provider: pypi
  user: ROldford
  password:
    secure: Ng+DnLfFhza5l+QMLHgM6zRj5X2gN+cyc8AxsGk+Am1Z8SJUEHwDz4ZvA0Pym2TNYqPDC3p3UCbmDUf46y+MwL6FG+09ykGONjCUs5FHc531Uk2W3nEC9A3YR5OD1azBGS9r21Go7E9Kgq0mkK615T9BVhXYpTQitpLRlLkkIgBcNUahH5hlsUnTkl0voYXWt7WpHnFakhvdGj+rucVe9QYcsoGGu+4Y1zFsYkb67P/wKX8HARcrOYu8ueU5CQapGkSqMUSKlRmzyp2eFjHpr0kd4nN8gXdF8xx5m9yZnG3jr/Kl3dAkVapfqHOaNWS2pJ6Dq5a13zZ6no9Jt/PEhe32XZYyPxQQfi4ah4tGD26F3ZW2/QlQ6oyLAP/4oHxj6gUcirUkQwBqYF+W5gSQpR70knkD1fdkG8OjQg8cC1Xn1bwEBOvcjHycfem0dTCrHTXz7G0G7aW+5AQIhhGD/jelDmeyc8pX5jBv2qsk/eMztX/VmRu/zIPi0bt2p91zCFSTy/j/Moo6ml2mLkUchEse+xwvFLX59vA6dKyzHDpp7viWtfzTx8UqLgISpAqYN5uzDP/dj9+Lg0Hiq1uceqHOTmX3oW9v0820CdqSLpgvFrLY2rHKKWTf3535GgRqQg7X+fNKdtgnICD7/0Y++1rEXyj9xiPXwHHk6JmQMZ0=
  on:
    tags: true
    branch: master
install: pip3 install -r requirements.txt
script: python setup.py test
