language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
deploy:
  provider: pypi
  user: ROldford
  password:
    secure: sBVj3TnjQp5UEHxG0tGgS/zeCa2xdpqvjPygkyhPx3aSGaQZ9/fi+DOhs7b6VP4l9Nup1Xz1iJcGqI93AIYNU7PCWnjBJWtPSnaDuaPzqC533wrw7JTC/vVXnD2OMVcRhFmSua38ng2CrVdIL2Kif5a3a8PLFfgZyqBVQY0iy6v7qk6dGMkkJBUHmVqYrZ/E/W160L6bGWfVEGLXod9QfFPhpFEBUzsc5442vt0DfQpqx5Oq1fp6XEKP/HlFazW3Y4qyg9BaQZXx4LX7wgHfzz6aymS2By9OoeiEr5WxGLB7i4vJk5nh6Wn1JyJxIN7nohqnOeh1WMg6M5jWxBchzZZWSdnychJ+cDisdCgfHLJoGMWGQ/5qUJDmFACOSZpWINgydS75HcoNwFxUvkzOfsHeyjJzWLs46qmYLF/0/+vZfbNM2XiFnl/C3mdId1nqxIIC8E8mnv1QGMXugnge99oakWDjLfqtEnC15w+g4zUGsQWP8DTND5iQjNzzqS3sKyX3RD+bDR6C9tVcP73iizSvNkE6E2+LVUc7NxW5k4yFOYt7LtEYyP0PwsK136wHVh82mP6dmcS3CSjSAmJH01ysrwA55nE+QG34Oe4eRiWCoYPsTpP+ozjFLAt5dAOOpEYcDlKACIBkoa8BS2a+Q9c78ULEJ+OUzzgfAbprPu0=
  on:
    tags: true
    branch: master
    python: '3.7'
install: pip3 install -r requirements.txt
script: python setup.py test
