language: python
python:
- 3.6
jobs:
  include:
  - python: 3.7
    dist: xenial
os: linux
deploy:
  provider: pypi
  username: ROldford
  password:
    secure: "OdOuvk980zmRIUtWD9yoXxGG3N3VJmx+VAXXhJYdpkqQwG4Scv0bJP5d7hH2BQD3HKSEZhPu9VhZ2z8RX9FrnFgQzjaPmLh40GJYWSl42uKuYTyE4Hgvan1+CqcTbCJDc6LzbdKW08cUigpmtrLHLrnH7q/upSaQCmA5r0nt9I0sImk9o8F2FjC35lWKv6UooodaHnELyQfuYyuPrTxiHO/TtR/QrnERg1coED7OsxXScIAzu/i6qv5SglkZtqFsQaGwlzDOXNRonSxRyqiqdhbfJ2wYaUtuaHR2LNe/Us/NTDhU2LsfhrrQZp9jheWj7bpiSVOngSYXwylRqTmGb3UVppUROIdQP2+L0Wyt1Mj53khcsiHbrYgFL0hn4XS6ixDQ+Na6JW7nKeY+huGxq7M2Gbynw1DuFBjKoBxp89UK8OOMHt8w7vdISIBjT6AyBTsGQpDPHU6VjDcDiN9RbnWEGnkNex0HI+YvjlnIHwTs6w9xgkJnCbOJbeh5zMYtPmIUFiD/m4shUIJQ16Aew7xDFWSRtIl9r3o80/Jj6Bi3LEQyyRFMHCWaKTPlokBC2cQFO6sCJ+Q85NG8IsvFETqJ1b9QdXPmAteWMd0s+tFwx/NPcF2xbwbEEf7tTX7J1RSkWbn4TObSXwayj0u1Ltpk4tY1QvytGrKrPk6AAy0="
  on:
    tags: true
    branch: master
    python: '3.7'
install: pip3 install -r requirements.txt
script: python setup.py test
