language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
deploy:
  provider: pypi
  user: ROldford
  password:
    secure: X9NqyPS10U3+cvy3AiAkVWrTRiWkYWLBGPJTl+pJG39DXBOg9m9ZkryxdQrTDNqJ3sdpuH7l0yIx+fFxHrtrvzia3xJNjV3tY99c+9QUL9K3lW1DgdZD8WuPoyhQDGIZlwgYwTV4KY6ZsXRTy2cyvEB85HPyab9/3eYBkZV989VBydyeMm52TgP8P7DDp8FXuduVTgMQcCNOBexNCIjDpPcmYSuOR8H53F/2Q6g/fSMqIXiachoWTos0o4m3Wqrq7i5Nzzw0xHqk4TaHAyu7c0ok4i9zj/kNEjY/3pMmtRKaJdx0qcBFmSGsoGGg2eYBBp1/v/Kz1duYJhH/6g+1HxDGHH0aqGDqOfvqQnRgahsLNtlPBQxwYCrSfhzMHx7wpXg56JyoqDxYlUnZz/68tcUGhNOOeZ64ork+6WmkkdMp+1t15j9FFF+0+CS38+Vkn99IPHmS2+PotwWXyq0IvQY32m8RkOQHS5umzp9ukFHdQ0Yy1IecaYiElhIPQSkbwKdC7FAWU+njGdHw4MsTKsJmg6wwmEIOxhCUE5w7jZOEo2Nf0OQ8B7iE9kN4iufzhewELtHu+JDVjmC1aa6sLrj3XuEMD8eyLJSZ6xdvnWav0g8PeQa89Nj76zqC8NvYeASy2kvX52927yZuL091+y4z69OVPmejUu+uYzmQ+xU=
  on:
    tags: true
    branch: master
    python: '3.7'
install: pip3 install -r requirements.txt
script: python setup.py test
