# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

deploy:
    provider: pypi
    user: "ROldford"
    password:
        secure: "lOkwJGJyLUZocN2rKPAKRO3gGPE89ri+6G3/F77gW6+zWkXKTqaBChImpTCooYQCWf3UMyJt1Pvxuf4Y4ooyzMG+fcDK/EHyCcEzfvO1WmeuCnxiXrrDFXkiT7b1euzYkPdHSts7GbhCkG0iKCLFhtqVL8u/pO4eBLR9/qrT3xBZn84RbJjbU28+5TeENpjx0e0ebbxQv93mMiPtjv/0Oc6X/ZaZLbLBWj3qy17FUPdLuGfwTWd+heN0tPzcgrNoDxRpCG9K6VO2wiiG11Psw4+DtCRRR/l/XkXSI3f9Ckqtn4xjcfZivj8qBCYvkYCmOvsqVBLPhnK9WWnYLgRUGSJd7E7YPeRZ1/+rtij4aFmR2YOpz3dbFYJljahsWYBO+hA6Wokmr5zjOdzr0y+0EruR/Y0i0GRONrOoThfTPWB7zq4JiR8KEa5pFTeTU4OWUaV+QgWb/XsH8/2VADNUsfUAoyPNU7GHXUFsNZ5oU6TZHCP4BXhjciysuQH+fD9lmaGM45K3PyfA1GVJSrvoyhgYfx5ORVr7GT610QtGRQEuqUJmTDJWh8Lrq/cjWisNUdGlMmAkSj3lQ+11NKgLc2O/Oq/0GLPeIeSqfZRHPFoa2yEl63qzWaYDhmeuSVNEuJ+LJyFntIuDqB3DlnuiGorcZeJqvOlkwlKEKHwdHTo="
    on:
        tags: true
        branch: master


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip3 install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: python setup.py test
